apiVersion: v1
kind: Service
metadata:
  name: swiggy-app
  namespace: default  # Add this line to specify the namespace
  labels:
    app: swiggy-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: swiggy-app
